## 2. Keras를 이용한 전처리

토큰화 함수를 이용하자. NLTK 토큰화 모듈과는 약간 다르다.

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
text = ['I love my dog', 'I, love my cat', 'You love my dog!']

t  = Tokenizer()
t.fit_on_texts(text)
print("단어집합 : ", t.word_index) 

단어집합 :  {'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'you': 6}


In [3]:
seq = t.texts_to_sequences(text)
print('text:', text) 
print('seq :', seq) 

text: ['I love my dog', 'I, love my cat', 'You love my dog!']
seq : [[3, 1, 2, 4], [3, 1, 2, 5], [6, 1, 2, 4]]


원-핫 인코딩 

In [4]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [5]:
text = ["cat", "dog", "cat", "bird"]  # 우리가 변환하고 싶은 텍스트
total_pets = ["cat", "dog", "turtle", "fish", "bird"]  # 단어 집합
print("text=", text)

text= ['cat', 'dog', 'cat', 'bird']


In [6]:
mapping = {}     # 변환에 사용되는 딕셔너리를 만든다. 
for x in range(len(total_pets)):
  mapping[total_pets[x]] = x	#“cat"->0, "dog"->1, ...
print(mapping)

{'cat': 0, 'dog': 1, 'turtle': 2, 'fish': 3, 'bird': 4}


In [7]:
for x in range(len(text)):    # 단어들을 순차적인 정수인덱스fh 
    text[x] = mapping[text[x]]
print("text=", text)

text= [0, 1, 0, 4]


In [8]:
one_hot_encode = to_categorical(text) # 정수인덱스를 원-핫 인코딩 
print("text=", one_hot_encode)

text= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


패딩(padding)

In [1]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
# text = ['I love my dog', 'I, love my cat', 'You love my dog!']
text = ['토큰 이해함. ㅎㅎ', 
        '정수 인코딩이 원-핫 인코딩인가? 가물 가물! ㅋㅋ', 
        '이제 슬슬 졸린다. 자연어 처리에서 패딩을 배우고 있는데 이게 뭐지?']
tokenizer  = Tokenizer()
tokenizer.fit_on_texts(text)
word_inx = tokenizer.word_index 

In [3]:
int_enc = tokenizer.texts_to_sequences(text) 
print('정수 인코딩:\n\n', int_enc)
max_length = 15
pad_int_enc = pad_sequences(int_enc, maxlen=max_length, padding='pre')
print("\npre 패딩:\n\n",pad_int_enc)
pad_int_enc = pad_sequences(int_enc, maxlen=max_length, padding='post')
print("\npost 패딩:\n\n", pad_int_enc)

정수 인코딩:

 [[2, 3, 4], [5, 6, 7, 8, 9, 1, 1, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]

pre 패딩:

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  2  3  4]
 [ 0  0  0  0  0  0  0  5  6  7  8  9  1  1 10]
 [ 0  0  0  0  0 11 12 13 14 15 16 17 18 19 20]]

post 패딩:

 [[ 2  3  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  6  7  8  9  1  1 10  0  0  0  0  0  0  0]
 [11 12 13 14 15 16 17 18 19 20  0  0  0  0  0]]
